name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish X86
      run: dotnet publish --configuration Release --framework net5 --runtime win-x86 --self-contained true
      
    - name: Publish X64
      run: dotnet publish --configuration Release --framework net5 --runtime win-x64 --self-contained true
      
    - name: Upload X86 Artifact
      uses: actions/upload-artifact@v2
      with:
       name: Vb6VirtualRegistry X86
       path: Vb6VirtualRegistry/Vb6VirtualRegistry/bin/Release/netcoreapp3.1/win-x86/publish/Vb6VirtualRegistry.exe
